### ISSUE TITLE
Stop motion when collisions are detected

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#36] opened 2014-02-28 05:52 UTC
https://github.com/start-jsk/rtmros_common/issues/247
@kenji0919

**Comment by 130s** [comment] 2014-04-30 10:27
I take this over

**Comment by 130s** [comment] 2014-05-03 00:18
Title changed, becauase servo-off at collision situation might just make things even worse by releasing held objects etc.
- old) servo off (or stop motion) when collisions are detected
- new) Stop motion when collisions are detected

After https://github.com/start-jsk/rtmros_hironx/issues/89 is merged, which is a visualizer of detected collision, we can add a feature to stop the motion (maybe in `hrpsys_ros_robotics`). Also, related to the comment https://github.com/start-jsk/rtmros_hironx/issues/34#issuecomment-42043228, we need a "stop" feature in the upstream (`hrpsys-base` is the good one to ask at).

**Comment by 130s** [comment] 2014-05-03 00:29
[Ticketed](https://github.com/fkanehiro/hrpsys-base/issues/215)

**Comment by k-okada** [comment] 2014-05-03 16:52
this is always discussion on which is better because servo off has less
chance to break robot (because another approach is that robot have chance
to stop motion even if there are collision, due to model error, that means
the servo system keep running and increase motor/circuit temperature and
may lead to  burn), but offcourse we do not want to drop off the
tools/object if servo off. Usually academic research says ok for servo off
and industrial people ok with stop motion, because in the industrial
people, they think there are always one person who hold emergency button,
when ever robot stops motion, then main power can cut off by human, but is
is not realistic for small lab.
- old) servo off (or stop motion) when collisions are
- new) Stop motion when collisions are detected

**Comment by 130s** [comment] 2014-05-05 08:08
Thank you for the valuable summary (@fkanehiro cites the similar concern at https://github.com/fkanehiro/hrpsys-base/issues/215#issuecomment-42092017 as well). Humbly speaking I have no idea what the ultimate decision must become like, but at this moment it looks like the discussion diverges after good length of period, so I'd suggest to add first a small, simple feature to `Stop Motion` to give users more options (and also we can test and evaluate the feature). Thoughts anyone?

**Comment by k-okada** [comment] 2014-05-05 17:21
currently you can achieve stop motion by
- get current angle vector
- send that data to the robot with time = 0.1 ( I'm not sure if time = 0 works)

so you can implement this in hironx_client.py level and may be this is good starting point.

**Comment by k-okada** [comment] 2014-05-05 17:21
Of course, if you already working on this, you do have to stop that.

**Comment by k-okada** [comment] 2014-07-11 02:22
@130s, @emijah what does `stop` mean? if this is just servo off, then I can fix soon, if this means stop motion and need to resume, we have to wait for https://github.com/fkanehiro/hrpsys-base/issues/215 discussion

**Comment by 130s** [comment] 2014-07-11 07:32
> @130s, @emijah what does stop mean? if this is just servo off, then I can fix soon, if this means stop motion and need to resume, we have to wait for fkanehiro/hrpsys-base#215 discussion

I meant `stop motion, resume` as per the title, and wonder what I can do to proceed https://github.com/fkanehiro/hrpsys-base/issues/215 discussion.

**Comment by k-okada** [comment] 2014-07-11 13:29
i think https://github.com/fkanehiro/hrpsys-base/issues/215 may takes long 
for both discussion and implementation, so my suggestion is to start with 
`just stop` function.

**Comment by DaikiMaekawa** [comment] 2014-12-21 16:39
I took over being in charge of this issue.

**Comment by emijah** [comment] 2014-12-22 01:41
I think servo-stop is best, because the purpose of this collision detection is to prevent collision, so the problem is detected in advance. If there was an unforeseen collision, it's probably best to leave it to the safety features of the servo control, and let them switch the servo motors off.
Ideally, only the servo detecting excessive force should switch off, and allow switching on again, but the current system cuts the power supply to all motors so this is not possible.

**Comment by k-okada** [comment] 2014-12-22 14:25
nice, 
please follow discussion here -> 
https://github.com/start-jsk/rtmros_common/pull/618, 
https://github.com/fkanehiro/hrpsys-base/issues/431, 
https://github.com/fkanehiro/hrpsys-base/issues/425. They do not reach to 
the final solution, but it might be interesting to you.

I always like to start from most easiest and simplest approach and move to 
more difficult version, so
- running collision detector component on ubuntu machine, when it detect 
  collision, just to send servo off command (
  https://github.com/fkanehiro/hrpsys-base/issues/425#issuecomment-67189494, 
  https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/hrpsys_ros_bridge/hrpsys_dashboard.py#L178
  )
- running collision detector component on QNX machine, this "should" work, 
  but not sure, because vclip is not able to work on 32bit machine until 
  recently (https://github.com/fkanehiro/hrpsys-base/pull/352), so we're 
  afraid that there might be some problem on QNX.
- running collision detector plugin inside of hrpsys(rtcd), this fill 
  suppress  motor commend when it find collision, so you do have to "servo 
  off" in this setup

Also using fcl (https://github.com/flexible-collision-library/fcl) instead 
of vclip is also related topic (
https://github.com/fkanehiro/hrpsys-base/issues/97)

## 

◉ Kei Okada

**Comment by 130s** [comment] 2017-05-22 23:29
See #250, which may or may not be the complete replacement of this. Feel free to reopen if further discussing is needed.

**Closed as completed by 130s** 2017-05-22 23:29 UTC
Labels: enhancement, critical
